---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx-pod
      labels:
        type: app
    spec:
      containers:
        - name: mynginx
          image: nginx
...
