#there are 2 type of volumes
#1 is emptyDir{}
#2 is PersistantVolume

# NOW WE SEE THE emptyDir{} 
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    author: ajay
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8888
      volumeMounts:
        - name: nginxvolume
          mountPath: /usr/share/nginx/html
  volumes:
    - name : nginxvolume
      emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myhttpd
        image: httpd
        volumeMounts:
          - name: httpdvolumes
            mountPath: /usr/local/apache2/htdocs
      volumes: 
        - name: httpdvolumes
          emptyDir: {}
...




