---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    name: ajay
spec:
  containers:
    - name: myhttpd
      image: httpd
  tolerations:
    - key: "slave1"
      operator: "Equal"
      value: "slave2"
      effect: "NoSchedule"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: app
    spec:
      containers:
        - name: mytomcat
          image: tomcat
      tolerations:
        - key: "slave3"
          operator: "Equal"
          value: "slave4"
          effect: "NoSchedule"
                      
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-new
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-new
    spec:
      containers:
        - name: mynginx
          image: nginx
      tolerations:
        - key: "slave5"
          operator: "Equal"
          value: "slave6"
          effect: "NoSchedule"
        
                          
...
