#we use volume concept in deployment by using statefulset ... 
# in statefulset we use headless service object 
---
# see headless first
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    apps: mysql
spec:
  clusterIP: None
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
---
# see statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: task-pv-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
...
