---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: ajay
spec:
  containers:
  - name: mynginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ajay
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: ajay
    spec:
      containers:
        - name: myjenkins
          image: jenkins/jenkins
          resources:
            requests:
              memory: "120Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "500m"
...
