---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: nginx-pod
      labels:
        type: app
    spec:
      containers:
        - name: mynginx
          image: nginx
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: app
spec:
  ports:
    - port: 80
  selector:
    type: app
...
