---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: httpd-daemonset
spec:
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest  # Apache HTTP Server image from Docker Hub (latest version)
        ports:
        - containerPort: 80
          hostPort: 5555  # Port exposed by the HTTP server container
        # Add other configurations (volume mounts, environment variables, etc.) as needed
...
