---
apiVersion: v1
kind: Namespace
metadata:
  name: test-nv
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  namespace: test-nv
  labels:
    type: app
spec:
  replicas: 1
  template:
    metadata:
      name: nginx-pod
      labels:
        type: app
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  namespace: test-nv  
  labels:
    type: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app1
  template:
    metadata:
      name: httpd-pod
      labels:
        type: app1
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8888
---                
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  namespace: test-nv
  labels:
    type: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app2
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: app2
    spec:
      containers:
        - name: mytomcat
          image: tomcat
          ports:
            - containerPort: 8080
              hostPort: 1111


