---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    type: app
type: Opaque
stringData:
  password: ajayy
  user: myuser
  db: mydb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: ajay
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ajay
  template:
    metadata:
      name: postgres-pod
      labels:
        name: ajay
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    author: ajay
spec:
  replicas: 1
  selector:
    matchLabels:
      author: ajay
  template:
    metadata:
      name: mysql-pod
      labels:
        author: ajay
    spec:
      containers:
        - name: mymysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
...
                                   
