---
apiVersion: v1
kind: Service
metadata:
  name: load-pod
  labels:
    type: app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 5555
      nodePort: 30012
  selector:
    name: ajay
---
apiVersion: v1
kind: Service
metadata:
  name: load-deployment
  labels:
    type: app1
spec:
  type: LoadBalancer
  ports:
  - port: 6666
    targetPort: 8080
    nodePort: 30016
  selector:
    app: ajju
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: ajay 
spec:
  containers:
  - name: mynginx
    image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
spec:
  selector:
    matchLabels:
      app: ajju 
  template:
    metadata:
      labels:
        app: ajju
    spec:
      containers:
      - name: mytomee
        image: tomcat

...














