---
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip
spec:
  ports:
  - port: 8888
    targetPort: 8080
  selector:
    app: ajay
---    
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip
spec:
  ports:
  - port: 5555
    targetPort: 80
  selector:
    name: ajay
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: ajay
spec:
  containers:
  - name: mynginx
    image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  selector:
    matchLabels:
      app: ajay
  template:
    metadata:
      labels:
        app: ajay
    spec:
      containers:
      - name: myjenkins
        image: jenkins/jenkins
...
     



